{
  "openapi": "3.0.1",
  "info": {
    "title": "Terminals Management API v1",
    "contact": {
      "name": "Antonello Provenzano",
      "email": "antonello@deveel.com"
    },
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://api.ocm.deveel.net"
    }
  ],
  "paths": {
    "/": {
      "post": {
        "tags": [
          "terminal"
        ],
        "summary": "Creates a Terminal",
        "operationId": "createTerminal",
        "security": [
          {
            "oauth2": [
              "create:terminal"
            ]
          }
        ]
      }
    },
    "/{id}": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Gets a Terminal",
        "operationId": "getTerminal",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "terminal"
        ],
        "summary": "Deletes a Tenant's Terminal",
        "operationId": "removeTerminal",
        "security": [
          {
            "oauth2": [
              "delete:terminal"
            ]
          }
        ]
      }
    },
    "/page": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Gets a page of Terminals",
        "operationId": "getTerminalPage",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/lookup": {
      "post": {
        "tags": [
          "terminal"
        ],
        "summary": "Looks up a Terminal",
        "operationId": "lookupTerminal",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/{id}/state": {
      "put": {
        "tags": [
          "terminal"
        ],
        "summary": "Changes the Status of a Terminal",
        "operationId": "changeTerminalStatus",
        "security": [
          {
            "oauth2": [
              "update:terminal"
            ]
          }
        ]
      }
    },
    "/{id}/role": {
      "put": {
        "tags": [
          "terminal"
        ],
        "summary": "Changes the Role of a Terminal",
        "operationId": "changeTerminalRole",
        "security": [
          {
            "oauth2": [
              "update:terminal"
            ]
          }
        ]
      }
    },
    "/inventory/request": {
      "post": {
        "tags": [
          "terminal"
        ],
        "summary": "Requests a Terminal",
        "operationId": "requestTerminal",
        "security": [
          {
            "oauth2": [
              "request:terminal"
            ]
          }
        ]
      }
    },
    "/provider": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "List All Supported Providers",
        "operationId": "listProviders",
        "security": [
          {
            "oauth2": [
              "read:terminal_provider"
            ]
          }
        ]
      }
    },
    "/provider/{code}": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Get a Provider by its Code",
        "operationId": "getProvider",
        "security": [
          {
            "oauth2": [
              "read:terminal_provider"
            ]
          }
        ]
      }
    },
    "/request/{id}": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Gets a Terminal Assignment Request",
        "operationId": "getTerminalRequest",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/request": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Gets a page of Terminal Assignment Requests",
        "operationId": "getTerminalRequests",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "read:inventory": "Read access to an inventory of resources",
              "write:inventory": "Write access to an inventory of resources",
              "read:tenant": "Read access to the Tenant information",
              "write:tenant": "Write access to tenant information",
              "create:terminal": "Create new server terminals",
              "read:terminal": "Read access to the information of existing terminals",
              "delete:terminal": "Delete existing terminals",
              "update:terminal": "Update the information of existing terminals",
              "request:terminal": "Request the assignment of a terminal from the inventory",
              "read:terminal_requests": "Read access to the requests of assignments of terminals",
              "assign:terminal": "Assign terminals to tenants"
            }
          },
          "authorizationCode": {
            "authorizationUrl": "https://deveel.eu.auth0.com/authorize",
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "read:inventory": "Read access to an inventory of resources",
              "write:inventory": "Write access to an inventory of resources",
              "read:tenant": "Read access to the Tenant information",
              "write:tenant": "Write access to tenant information",
              "create:terminal": "Create new server terminals",
              "read:terminal": "Read access to the information of existing terminals",
              "delete:terminal": "Delete existing terminals",
              "update:terminal": "Update the information of existing terminals",
              "request:terminal": "Request the assignment of a terminal from the inventory",
              "read:terminal_requests": "Read access to the requests of assignments of terminals",
              "assign:terminal": "Assign terminals to tenants"
            }
          }
        }
      },
      "apiKey": {
        "type": "apiKey",
        "name": "X-API-KEY",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "oauth2": [
        "read:inventory",
        "write:inventory",
        "read:tenant",
        "write:tenant",
        "create:terminal",
        "read:terminal",
        "delete:terminal",
        "update:terminal",
        "request:terminal",
        "read:terminal_requests",
        "assign:terminal"
      ]
    },
    {
      "apiKey": [ ]
    }
  ]
}