{
  "openapi": "3.0.1",
  "info": {
    "title": "Security Management API v1",
    "contact": {
      "name": "Antonello Provenzano",
      "email": "antonello@deveel.com"
    },
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://api.ocm.deveel.net"
    }
  ],
  "paths": {
    "/api_client": {
      "post": {
        "tags": [
          "client"
        ],
        "summary": "Creates an API Client",
        "operationId": "createApiClient",
        "security": [
          {
            "oauth2": [
              "create:client"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "client"
        ],
        "summary": "Gets a Page of API Clients",
        "operationId": "getApiClientPage",
        "security": [
          {
            "oauth2": [
              "read:client"
            ]
          }
        ]
      }
    },
    "/api_client/{id}": {
      "get": {
        "tags": [
          "client"
        ],
        "summary": "Gets an API Client",
        "operationId": "getApiClient",
        "security": [
          {
            "oauth2": [
              "read:client"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "client"
        ],
        "summary": "Deletes an API Client",
        "operationId": "deleteApiClient",
        "security": [
          {
            "oauth2": [
              "delete:client"
            ]
          }
        ]
      }
    },
    "/api_client/{id}/status": {
      "put": {
        "tags": [
          "client"
        ],
        "summary": "Sets the Status of an API Client",
        "operationId": "setApiClientStatus",
        "security": [
          {
            "oauth2": [
              "update:client"
            ]
          }
        ]
      }
    },
    "/api_client/{clientId}/keyRotation": {
      "put": {
        "tags": [
          "client"
        ],
        "summary": "Rotate the Key of an API Client",
        "operationId": "rotateApiClientKey",
        "security": [
          {
            "oauth2": [
              "update:client"
            ]
          }
        ]
      }
    },
    "/app": {
      "post": {
        "tags": [
          "client"
        ],
        "summary": "Creates a Client",
        "operationId": "createApplication",
        "security": [
          {
            "oauth2": [
              "create:client"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "client"
        ],
        "summary": "Gets a Page of Clients",
        "operationId": "getApplicationPage",
        "security": [
          {
            "oauth2": [
              "read:client"
            ]
          }
        ]
      }
    },
    "/app/{id}": {
      "get": {
        "tags": [
          "client"
        ],
        "summary": "Gets a Client",
        "operationId": "getApplication",
        "security": [
          {
            "oauth2": [
              "read:client"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "client"
        ],
        "summary": "Deletes a Client",
        "operationId": "deleteApplication",
        "security": [
          {
            "oauth2": [
              "delete:client"
            ]
          }
        ]
      }
    },
    "/app/{id}/status": {
      "put": {
        "tags": [
          "client"
        ],
        "summary": "Sets the Status of a Client",
        "operationId": "setApplicationStatus",
        "security": [
          {
            "oauth2": [
              "update:client"
            ]
          }
        ]
      }
    },
    "/role": {
      "get": {
        "tags": [
          "role"
        ],
        "summary": "Get a All of Roles",
        "operationId": "getAllRoles",
        "security": [
          {
            "oauth2": [
              "read:role"
            ]
          }
        ]
      }
    },
    "/role/{id}": {
      "get": {
        "tags": [
          "role"
        ],
        "summary": "Get a Role",
        "operationId": "getRole",
        "security": [
          {
            "oauth2": [
              "read:role"
            ]
          }
        ]
      }
    },
    "/role/{id}/grant": {
      "get": {
        "tags": [
          "role"
        ],
        "summary": "Get the Grants of a Role",
        "operationId": "getRoleGrants",
        "security": [
          {
            "oauth2": [
              "read:role"
            ]
          }
        ]
      }
    },
    "/user": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Create a New User",
        "operationId": "createUser",
        "security": [
          {
            "oauth2": [
              "create:user"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Gets a Page of Users",
        "operationId": "getUserPage",
        "security": [
          {
            "oauth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/user/{id}": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Gets a User",
        "operationId": "getUser",
        "security": [
          {
            "oauth2": [
              "read:user"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Deletes a User",
        "operationId": "deleteUser",
        "security": [
          {
            "oauth2": [
              "delete:user"
            ]
          }
        ]
      }
    },
    "/user/me": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Gets the Current User",
        "operationId": "getMe",
        "security": [
          {
            "oauth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/user/{id}/status": {
      "put": {
        "tags": [
          "user"
        ],
        "summary": "Sets the Status of a User",
        "operationId": "setUserStatus",
        "security": [
          {
            "oauth2": [
              "write:tenant",
              "update:user"
            ]
          }
        ]
      }
    },
    "/user/{id}/grant": {
      "put": {
        "tags": [
          "user"
        ],
        "summary": "Grant Permissions to a User",
        "operationId": "grantUser",
        "security": [
          {
            "oauth2": [
              "grant:user"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Get the Grants of a User",
        "operationId": "getUserGrants",
        "security": [
          {
            "oauth2": [
              "read:user"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "create:account": "Register a new account",
              "create:tenant": "Create new Tenants",
              "update:tenant": "Update information of existing Tenants",
              "read:tenant": "Read access to the Tenant information",
              "delete:tenant": "Delete existing tenants",
              "create:user": "Create new users within a Tenant",
              "read:user": "Read access to user information",
              "update:user": "Update user information",
              "delete:user": "Delete existing users",
              "invite:user": "Invite an individual to subscribe",
              "create:client": "Create new client applications",
              "delete:client": "Delete existing client applications",
              "update:client": "Update the information of existing client applications",
              "read:client": "Read access to client applications",
              "read:client_credentials": "Read access to the credentials of client applications"
            }
          },
          "authorizationCode": {
            "authorizationUrl": "https://deveel.eu.auth0.com/authorize",
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "create:account": "Register a new account",
              "create:tenant": "Create new Tenants",
              "update:tenant": "Update information of existing Tenants",
              "read:tenant": "Read access to the Tenant information",
              "delete:tenant": "Delete existing tenants",
              "create:user": "Create new users within a Tenant",
              "read:user": "Read access to user information",
              "update:user": "Update user information",
              "delete:user": "Delete existing users",
              "invite:user": "Invite an individual to subscribe",
              "create:client": "Create new client applications",
              "delete:client": "Delete existing client applications",
              "update:client": "Update the information of existing client applications",
              "read:client": "Read access to client applications",
              "read:client_credentials": "Read access to the credentials of client applications"
            }
          }
        }
      },
      "apiKey": {
        "type": "apiKey",
        "name": "X-API-KEY",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "oauth2": [
        "create:account",
        "create:tenant",
        "update:tenant",
        "read:tenant",
        "delete:tenant",
        "create:user",
        "read:user",
        "update:user",
        "delete:user",
        "invite:user",
        "create:client",
        "delete:client",
        "update:client",
        "read:client",
        "read:client_credentials"
      ]
    },
    {
      "apiKey": [ ]
    }
  ]
}