{
  "openapi": "3.0.1",
  "info": {
    "title": "Channel Management API v1",
    "contact": {
      "name": "Antonello Provenzano",
      "email": "antonello@deveel.com"
    },
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://api.ocm.deveel.net"
    }
  ],
  "paths": {
    "/request/{id}": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a Channel Assignment Request",
        "operationId": "getChannelRequest",
        "security": [
          {
            "oauth2": [
              "request:channel"
            ]
          }
        ]
      }
    },
    "/request": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets all Channel Assignment Requests",
        "operationId": "getChannelRequests",
        "security": [
          {
            "oauth2": [
              "request:channel"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "channel"
        ],
        "summary": "Requests the Assignment of a Channel",
        "operationId": "requestChannel",
        "security": [
          {
            "oauth2": [
              "request:channel"
            ]
          }
        ]
      }
    },
    "/schema": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets all the Channel Schemata",
        "operationId": "getAllChannelSchema",
        "security": [
          {
            "oauth2": [
              "read:inventory"
            ]
          }
        ]
      }
    },
    "/schema/{type}/{provider}": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Get a Channel Schema",
        "operationId": "getChannelSchema",
        "security": [
          {
            "oauth2": [
              "read:inventory"
            ]
          }
        ]
      }
    },
    "/": {
      "post": {
        "tags": [
          "channel"
        ],
        "summary": "Creates a new Channel",
        "operationId": "createChannel",
        "security": [
          {
            "oauth2": [
              "create:channel"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets all Channels",
        "operationId": "listAllChannels",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/{channelId}": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a Channel",
        "operationId": "getChannel",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "channel"
        ],
        "summary": "Deletes a Channel",
        "operationId": "deleteChannel",
        "security": [
          {
            "oauth2": [
              "delete:channel"
            ]
          }
        ]
      }
    },
    "/name/{channelName}": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a Channel by Name",
        "operationId": "getChannelByName",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/{channelId}/state": {
      "put": {
        "tags": [
          "channel"
        ],
        "summary": "Changes the State of a Channel",
        "operationId": "changeChannelState",
        "security": [
          {
            "oauth2": [
              "update:channel"
            ]
          }
        ]
      }
    },
    "/{channelName}": {
      "head": {
        "tags": [
          "channel"
        ],
        "summary": "Checks if a Channel Exists",
        "operationId": "channelExists",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/{channelId}/credentials": {
      "put": {
        "tags": [
          "channel"
        ],
        "summary": "Updates the Channel Credentials",
        "operationId": "updateChannelCredentials",
        "security": [
          {
            "oauth2": [
              "update:channel"
            ]
          }
        ]
      }
    },
    "/{channelId}/terminal": {
      "put": {
        "tags": [
          "channel",
          "terminal"
        ],
        "summary": "Adds a Terminal",
        "operationId": "addChannelTerminal",
        "security": [
          {
            "oauth2": [
              "update:channel"
            ]
          }
        ]
      }
    },
    "/{channelId}/terminal/{terminalId}": {
      "delete": {
        "tags": [
          "channel",
          "terminal"
        ],
        "summary": "Removes a Terminal",
        "operationId": "removeChannelTerminal",
        "security": [
          {
            "oauth2": [
              "update:channel"
            ]
          }
        ]
      }
    },
    "/{channelId}/settings": {
      "patch": {
        "tags": [
          "channel"
        ],
        "summary": "Updates the Settings of a Channel",
        "operationId": "updateChannelSettings",
        "security": [
          {
            "oauth2": [
              "update:channel"
            ]
          }
        ]
      }
    },
    "/page": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a page of Channels",
        "operationId": "getChannelPage",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/inventory/{channelId}": {
      "get": {
        "tags": [
          "channel",
          "inventory"
        ],
        "summary": "Gets a Channel from the Inventory",
        "operationId": "getChannelFromInventory",
        "security": [
          {
            "oauth2": [
              "read:inventory",
              "read:channel"
            ]
          }
        ]
      }
    },
    "/inventory": {
      "get": {
        "tags": [
          "channel",
          "inventory"
        ],
        "summary": "Gets a Page of Channels from the Inventory",
        "operationId": "getChannelInventoryPage",
        "security": [
          {
            "oauth2": [
              "read:inventory",
              "read:channel"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "read:inventory": "Read access to an inventory of resources",
              "write:inventory": "Write access to an inventory of resources",
              "read:tenant": "Read access to the Tenant information",
              "write:tenant": "Write access to tenant information",
              "read:channel": "Read access to the information of existing channels",
              "create:channel": "Create new channels",
              "update:channel": "Update the information of existing channels",
              "delete:channel": "Delete existing channels",
              "request:channel": "Request the assignment of a channel from the inventory",
              "assign:channel": "Assign channels to tenants",
              "read:channel_credentials": "Read access to the credentials of channels"
            }
          },
          "authorizationCode": {
            "authorizationUrl": "https://deveel.eu.auth0.com/authorize",
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "read:inventory": "Read access to an inventory of resources",
              "write:inventory": "Write access to an inventory of resources",
              "read:tenant": "Read access to the Tenant information",
              "write:tenant": "Write access to tenant information",
              "read:channel": "Read access to the information of existing channels",
              "create:channel": "Create new channels",
              "update:channel": "Update the information of existing channels",
              "delete:channel": "Delete existing channels",
              "request:channel": "Request the assignment of a channel from the inventory",
              "assign:channel": "Assign channels to tenants",
              "read:channel_credentials": "Read access to the credentials of channels"
            }
          }
        }
      },
      "apiKey": {
        "type": "apiKey",
        "name": "X-API-KEY",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "oauth2": [
        "read:inventory",
        "write:inventory",
        "read:tenant",
        "write:tenant",
        "read:channel",
        "create:channel",
        "update:channel",
        "delete:channel",
        "request:channel",
        "assign:channel",
        "read:channel_credentials"
      ]
    },
    {
      "apiKey": [ ]
    }
  ]
}